config/routes.rb
Rails.application.routes.draw do

get "sign_up" => "users#new", :as => "sign_up"
    resources :users
    resources :comments
    resources :sessions
    root :to => "articles#index"
    resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
     
     validates :title, presence: true,

                            length: { minimum: 5 }

        validates :content, presence: true,

                            length: { minimum: 10 }

        validates :status, presence: true

          scope :status_active, -> {where(status: 'off')}

          has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
 before_create :default_status

        belongs_to :article

        belongs_to :user

        validates :content, presence: true, length: { minimum: 10 }


        def default_status

            self.status = "not active"

        end

end

app/models/user.rb
 class User < ActiveRecord::Base


    before_create :add_activation_token

    def add_activation_token

        self.activation_token = SecureRandom.urlsafe_base64

        self.activation_status = "not activated"

    end

    include Humanizer

    /require_human_on :create/
    
        attr_accessor :password

        before_save :add_salt_and_hash


        validates :username, presence: true, uniqueness: true

        validates :email, presence: true, uniqueness: true

        validates :password, presence: true, on: :create,

        length: { minimum: 5 },

        confirmation: true


        def add_salt_and_hash

            unless password.blank?

                self.password_salt = BCrypt::Engine.generate_salt

                self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)

            end

        end

    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
         protect_from_forgery with: :exception


        helper_method :current_user, :check_current_user


        def current_user

            current_user ||= User.where("id = ? and activation_status = ?", session[:user], 'active').first

        end


        def check_current_user

            if current_user.blank?

                flash[:error] = "plase login first before run the action"

                redirect_to new_session_url

            else

                current_user

            end

        end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :check_current_user, only: [:new, :create, :edit, :update, :destroy]

respond_to do |format|
    format.js
  end
  
  def index
  	  @articles = Article.all
  end

  def new
  @article = Article.new
  end

   def edit

        @article = Article.find_by_id(params[:id])

    end

   def create

    @article = Article.new(params_article)

    if @article.save

        flash[:notice] = "Success Add Records"

        redirect_to action: 'index'

    else

        flash[:error] = "data not valid"

        render 'new'

    end

end

def update

 @article = Article.find_by_id(params[:id])

 if @article.update(params_article)

    flash[:notice] = "Success Update Records"

    redirect_to action: 'index'

 else

    flash[:error] = "data not valid"

    render 'edit'

 end

end

 def show

        @article = Article.find_by_id(params[:id])

        @comments = @article.comments.order("id desc")

        @comment = Comment.new

    end


  def destroy

    @article = Article.find_by_id(params[:id])

    if @article.destroy

        flash[:notice] = "Success Delete a Records"

        redirect_to action: 'index'

    else

        flash[:error] = "fails delete a records"

        redirect_to action: 'index'

    end

end

private

    def params_article

        params.require(:article).permit(:title, :content, :status)

    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_current_user, only: [:new, :create, :edit, :update, :destroy]


        def create

            respond_to do |format|

                @comment = Comment.new(params_comment)

                if @comment.save

  format.js {@comments = Article.find_by_id(params[:comment][:article_id]).comments.order("id desc")}

                else

                    format.js {@article = Article.find_by_id(params[:comment][:article_id])}

                end

            end

        end


        private

            def params_comment

                params.require(:comment).permit(:article_id, :user_id, :content, :status)

            end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def edit

        user = User.find_by_activation_token(params[:id])

        if user.try(:update,{activation_token: "", activation_status: "active"})

            flash[:notice] = "Your account has active"

            redirect_to root_url

        else

            flash[:notice] = "Wellcome to Rails 4"

            redirect_to root_url

        end

    end

def create

        username = params[:username]

        password = params[:password]

        user = User.where("username =? and activation_status =?", username, "active").first

        user_password = BCrypt::Engine.hash_secret(password, user.password_salt) unless user.blank?

        if !user_password.blank? and user.password_hash.eql? user_password

            session[:user] = user.id

            flash[:notice] = "Wellcome #{user.username}"

            redirect_to root_url

        else

            params[:username]

            flash[:error] = "Your data not valid"

            render "new"

        end

    end

 def destroy

        session[:user] = nil

        flash[:notice] = "logout session success"

        redirect_to root_url

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

    def new

    @user = User.new

	end

  def edit
  end

  

    def create

        @user = User.new(params_user)

        if @user.save

            begin

                ConfirmationMailer.confirm_email("#{@user.email}", @user.activation_token).deliver

            rescue

                flash[:notice] = "activation instruction fails send to your email"

            end

            flash[:notice] = "activation instruction has send to #{@user.email}"

            redirect_to root_url

        else

            flash[:error] = "data not valid"

            render "new"

        end

    end


    private

        def params_user

  params.require(:user).permit(:username, :email, :password, :password_confirmation, :humanizer_answer, :humanizer_question_id)

        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_comments.html.erb
 <% @comments.each do |comment| %>

        <p>

        <b><%= comment.user.try(:username) %></b>

        <br />

        <%= comment.content %>

        </p>

    <% end %>

app/views/articles/_form.html.erb
<%= form_for @comment, url: comments_path, remote: true do |f| %>

        <%= f.hidden_field :article_id, value: @article.id %>

        <% if current_user %>

            <%= f.hidden_field :user_is, value: current_user.id %>

        <% end %>

        <br/>

        <%= f.label :content %>

        <%= f.text_area :content, cols: 20, rows: 10 %>

        <br/>

        <%= f.submit :submit %>

    <% end %>

app/views/articles/edit.html.erb
<%= form_for @article do |f| %>

<%= f.label :title %>

<%= f.text_field :title %>

<br/>

<%= f.label :content %>

<%= f.text_area :content, cols: 20, rows: 10 %>

<br/>

<%= f.label :status %>

<%= f.radio_button :status, "active" %>

<%= label :article_status, 'active' %>

<%= f.radio_button :status, "off" %>

<%= label :article_status, 'off' %>

<br/>

<%= f.submit :submit %>

<% end %>


<div>

<%= link_to "back to index", articles_path %>

</div>

app/views/articles/index.html.erb
 <% @articles.each do |article| %>

<h3><%= article.title %></h3>

<p>

<%= article.content.truncate(20) %>

<%= link_to 'read more', article_path(article.id) %>

</p>

<h4>status : <%= article.status %></h4>

<p>

<span><%= link_to 'edit', edit_article_path(article.id) %><span>

 <span> | </span>

<span><%= link_to 'delete', article_path(article.id), method: "DELETE", data: {confirm: 'Delete this data ? '} %><span>
</p>

<hr/>

 <h4>

<% if !current_user %>

<%= link_to 'Log-in', new_session_path %>

<% else %>

Hello <%= current_user.username %>

<%= link_to 'Log-Out', session_path(current_user.id), method: "DELETE" %>

<% end %>

</h4>

<% end %>

app/views/articles/new.html.erb
 <%= form_for @article do |f| %>

<%= f.label :title %>

<%= f.text_field :title %>

<%= @article.errors[:title].first unless @article.errors[:title].blank? %>

<br/>

<%= f.label :content %>

<%= f.text_area :content, cols: 20, rows: 10 %>

<%= @article.errors[:content].first unless @article.errors[:content].blank? %>

<br/>

<%= f.label :status %>

<%= f.radio_button :status, "active" %>

<%= label :article_status, 'active' %>

<%= f.radio_button :status, "off", :checked => true %>

<%= label :article_status, 'off' %>

<br/>

<%= f.submit :submit %>

<% end %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>

    <p><%= @article.content %></p>

    <p><%= link_to 'back to index', articles_path %></p>


    <div id="form-comment">

        <%= render 'form' %>

    </div>


    <h4>Here the comments</h4>


    <div id="list-comments">

        <%= render 'comments' %>

    </div>

app/views/comments/create.js.erb
  <% if @comment.errors.present? %>

        $("#form-comment").html(" <%= j( render 'articles/form' ) %>");

    $($(".field_with_errors")[0]).append("<p class = 'message'> <%= escape_javascript( @comment.errors[:content].first ) %></p>");

        <% else %>

            $("#list-comments").html(" <%= j( render 'articles/comments' ) %>");

            $("#comment_content").val('');

            $("div.field_with_errors p.message").remove();

    <% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
  <!DOCTYPE html>

  <html>

    <head>

      <meta charset="utf-8">

      <meta httpequiv="XUACompatible" content="IE=edge">

      <meta name="viewport" content="width=devicewidth, initialscale=1">

       <title>Latihan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
    </head>

    <body style="padding-top:60px;">

      <!--bagian navigation-->
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">

  <div class="container">

    <div class="navbar-header">

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">

        <span class="sr-only">Toggle navigation</span>

        <span class="icon-bar"/>

        <span class="icon-bar"/>

        <span class="icon-bar"/>

      </button>

      <a href="#" class = "navbar-brand">MGRware</a>

    </div>

    <div class="collapse navbar-collapse">

    <ul class="nav navbar-nav navbar-right">
<li><%= link_to 'Home', articles_path %></li>

<li>a></li>
<li>c</li>
    </ul>

    </div>

  </div>

</div>


      <!-- Bagian Content -->

      <div class="container clearfix">

        <div class="row row-offcanvas row-offcanvas-left ">

          <!--Bagian Kiri-->

      <div class="col-xs-12 col-sm-3 side pull-lefthttp: sidebar-offcanvas" id="sidebar" role="navigation">

  <div class="">

    <p>gilang</p>

  </div>

</div>


          <!--Bagian Kanan-->

          <div id="main-content" class="col-xs-12 col-sm-9 main pull-right">

            <div class="panel-body">

              <%=yield%>
            </div>

          </div>

        </div>

      </div>

    </body>

  </html>

app/views/shared/head_nav.html.erb
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">

  <div class="container">

    <div class="navbar-header">

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">

        <span class="sr-only">Toggle navigation</span>

        <span class="icon-bar"/>

        <span class="icon-bar"/>

        <span class="icon-bar"/>

      </button>

      <a href="#" class = "navbar-brand">MGRware</a>

    </div>

    <div class="collapse navbar-collapse">

    <ul class="nav navbar-nav navbar-right">
<li>{{ HTML::link('/', 'Home')}}</li>
<li>{{ HTML::link('/', 'Gallery')}}</li>
<li><a href="#" class="article_link">Articles</a></li>
<li>{{link_to('users/create', 'Signup')}}</li>
 @if (Auth::check())

    <li>

    {{ Form::open(array('route' => array('sessions.destroy'), 'method' => 'delete')) }}

       {{ Form::submit('Logout', array('class' => 'btn btn-normal')) }}

    {{ Form::close() }}

    </li>

  @else

    <li>{{link_to('sessions/create', 'Login')}}</li>

  @endif
    </ul>

    </div>

  </div>

</div>

app/views/shared/left_nav.html.erb
<div class="col-xs-12 col-sm-3 side pull-lefthttp: sidebar-offcanvas" id="sidebar" role="navigation">

  <div class="">

    <p>gilang</p>

  </div>

</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

<%= f.label :username %>

<%= f.text_field :username %>

<%= @user.errors[:username].first unless @user.errors[:username].blank? %>

<br/>

<%= f.label :email %>

<%= f.text_field :email %>

<%= @user.errors[:email].first unless @user.errors[:email].blank? %>

<br/>

<%= f.label :password %>

<%= f.password_field :password %>

<%= @user.errors[:password].first unless @user.errors[:password].blank? %>

<br/>

<%= f.label :password_confirmation %>

<%= f.password_field :password_confirmation %>

<%= @user.errors[:password_confirmation].first unless @user.errors[:password_confirmation].blank? %>

<br/>
 <%= f.label :humanizer_answer, @user.humanizer_question %>

<%= f.text_field :humanizer_answer %>

<%= f.hidden_field :humanizer_question_id %>
<br/>
<%= f.submit %>

<% end %>